# Generated by Django 3.1 on 2020-11-23 18:03

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email Address')),
                ('is_superuser', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('', 'Please Select'), ('master', 'Master'), ('teacher', 'Teacher'), ('secretary', 'Secretary'), ('accountant', 'Accountant'), ('hr', 'Human Resource'), ('librarian', 'Librarian'), ('academy', 'Academy'), ('matron', 'Matron'), ('vehicle', 'Vehicle')], max_length=40, verbose_name='What primary role?')),
                ('created_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.customuser')),
                ('profile_pic', models.ImageField(default='profile_pics/user.svg', upload_to=users.models.profile_pic_filename, verbose_name='Profile Picture')),
            ],
        ),
    ]
