# Generated by Django 3.1 on 2020-11-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('', 'Please Select Role'), ('master', 'Master'), ('teacher', 'Teacher'), ('secretary', 'Secretary'), ('accountant', 'Accountant'), ('hr', 'Human Resource'), ('librarian', 'Librarian'), ('academy', 'Academy'), ('matron', 'Matron'), ('vehicle', 'Vehicle')], max_length=40, verbose_name='What primary role?'),
        ),
    ]
