# Generated by Django 3.1 on 2020-12-02 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=200, verbose_name='First Name')),
                ('middle_name', models.CharField(max_length=200, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last Name')),
                ('initial_expansion', models.CharField(max_length=200, verbose_name='Initial Expansion')),
                ('date_of_birth', models.DateField(verbose_name='Date Of Birth')),
                ('gender', models.CharField(choices=[('', 'Please select'), ('male', 'Male'), ('Female', 'Female')], max_length=10, verbose_name='Gender')),
                ('father_name', models.CharField(max_length=200, verbose_name='Father Name')),
                ('father_occupation', models.CharField(choices=[('', 'Please select'), ('Agriculture', 'Agriculture'), ('Banker', 'Banker'), ('Business', 'Business'), ('Doctor', 'Doctor'), ('Farmer', 'Farmer'), ('Fisherman', 'Fisherman'), ('Public Service', 'Public Service'), ('Private Service', 'Private Service'), ('Shopkeeper', 'Shopkeeper'), ('Driver', 'Driver'), ('Worker', 'Worker'), ('N/A', 'N/A')], max_length=200, verbose_name='Father Occupation')),
                ('mother_name', models.CharField(max_length=200, verbose_name='Mother Name')),
                ('mother_occupation', models.CharField(choices=[('', 'Please select'), ('Agriculture', 'Agriculture'), ('Banker', 'Banker'), ('Business', 'Business'), ('Doctor', 'Doctor'), ('Farmer', 'Farmer'), ('Fisherman', 'Fisherman'), ('Public Service', 'Public Service'), ('Private Service', 'Private Service'), ('Shopkeeper', 'Shopkeeper'), ('Driver', 'Driver'), ('Worker', 'Worker'), ('N/A', 'N/A')], max_length=200, verbose_name='Mother Occupation')),
                ('gurdian_name', models.CharField(max_length=200, verbose_name='Gurdian Name')),
                ('gurdian_occupation', models.CharField(choices=[('', 'Please select'), ('Agriculture', 'Agriculture'), ('Banker', 'Banker'), ('Business', 'Business'), ('Doctor', 'Doctor'), ('Farmer', 'Farmer'), ('Fisherman', 'Fisherman'), ('Public Service', 'Public Service'), ('Private Service', 'Private Service'), ('Shopkeeper', 'Shopkeeper'), ('Driver', 'Driver'), ('Worker', 'Worker'), ('N/A', 'N/A')], max_length=200, verbose_name='Gurdian Occupation')),
                ('Notes', models.TextField(verbose_name='Notes')),
                ('relationship', models.CharField(max_length=200, verbose_name='Relationship')),
                ('nationality', django_countries.fields.CountryField(default='TZ', max_length=2, verbose_name='Nationality')),
                ('religion', models.CharField(choices=[('', 'Please select'), ('christianity', 'Christianity'), ('islamic', 'Islamic'), ('hinduism', 'Hinduism'), ('Buddhism', 'Buddhism'), ('Others', 'Others')], max_length=20, verbose_name='Religion')),
                ('blood_group', models.CharField(choices=[('', 'Please select'), ('a+', 'A+'), ('o+', 'O+'), ('b+', 'B+'), ('ab+', 'AB+'), ('a-', 'A-'), ('o-', 'O-'), ('b-', 'B-'), ('ab-', 'AB-')], max_length=10, verbose_name='Blood Group')),
                ('student_type', models.CharField(choices=[('', 'Please select'), ('day', 'Day'), ('boarding', 'Boarding'), ('school bus', 'School Bus')], max_length=20, verbose_name='Student Type')),
                ('passport', models.ImageField(upload_to='passport', verbose_name='Upload Passport')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
