# Generated by Django 3.1 on 2020-12-04 07:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20201127_1654'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('punishment', models.CharField(max_length=100, null=True)),
                ('start_date', models.BooleanField(default=True)),
                ('end_date', models.BooleanField(default=True)),
                ('start_time', models.BooleanField(default=True)),
                ('end_time', models.BooleanField(default=False)),
                ('repeatable', models.BooleanField(default=True)),
                ('alert', models.PositiveSmallIntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Discipline's type",
                'verbose_name_plural': "Discipline's types",
                'ordering': ('punishment',),
            },
        ),
        migrations.CreateModel(
            name='Disciplines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('motif', models.TextField(blank=True, null=True)),
                ('fact_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive'), ('done', 'Done'), ('cancelled', 'cancelled')], default='Active', max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.CharField(blank=True, max_length=250, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discipline',
                'verbose_name_plural': 'Disciplines',
                'ordering': ('-fact_date',),
            },
        ),
        migrations.CreateModel(
            name='FeeCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('payment_mode', models.CharField(choices=[('', 'Please select'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('draft', 'Draft')], max_length=50, verbose_name='Payment Mode')),
                ('bank', models.CharField(blank=True, max_length=200)),
                ('cheque', models.CharField(blank=True, max_length=200)),
                ('receipt', models.CharField(max_length=200)),
                ('reg_fee_amount', models.DecimalField(decimal_places=0, max_digits=6)),
                ('vehicle_fee_amount', models.DecimalField(decimal_places=0, max_digits=6)),
                ('total', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostelAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(blank=True, choices=[('', 'Please select'), ('male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('date', models.DateField(blank=True, verbose_name='Allocation Date')),
                ('hostel_name', models.CharField(blank=True, max_length=200, verbose_name='Hostel Name')),
                ('block_name', models.CharField(blank=True, max_length=200, verbose_name='Block Name')),
                ('room_name', models.CharField(blank=True, max_length=200, verbose_name='Room Name')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalContactDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('p_address', models.TextField(verbose_name='Address')),
                ('p_postal_code', models.CharField(max_length=50, verbose_name='Postal Code')),
                ('p_phone', models.CharField(max_length=14, verbose_name='Phone')),
                ('student_email', models.EmailField(max_length=254, verbose_name='Student Email')),
                ('pr_address', models.TextField(verbose_name='Address')),
                ('pr_postal_code', models.CharField(max_length=50, verbose_name='Postal Code')),
                ('pr_phone', models.CharField(max_length=14, verbose_name='Phone')),
                ('parent_email', models.EmailField(max_length=254, verbose_name='Parent Address')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('school_name', models.CharField(max_length=100, verbose_name='School Name')),
                ('date_admission', models.DateField(verbose_name='Admission Date')),
                ('date_leaving', models.DateField(verbose_name='Leaving Date')),
                ('last_exam', models.CharField(max_length=200, verbose_name='Last Attending Examination')),
                ('other_qualification', models.CharField(max_length=200, verbose_name='Other Qualification')),
                ('remarks', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TransportAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Allocation Date')),
                ('vehicle', models.CharField(blank=True, max_length=200, verbose_name='Vehicle name')),
                ('route', models.CharField(blank=True, max_length=200, verbose_name='Route')),
                ('boarding_point', models.CharField(blank=True, max_length=200, verbose_name='Boarding Point Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='Notes',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='initial_expansion',
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='place_of_birth',
            field=models.CharField(default=2, max_length=200, verbose_name='Place of Birth'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('', 'Please select'), ('a+', 'A+'), ('o+', 'O+'), ('b+', 'B+'), ('ab+', 'AB+'), ('a-', 'A-'), ('o-', 'O-'), ('b-', 'B-'), ('ab-', 'AB-')], max_length=10, verbose_name='Blood Group'),
        ),
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('feecollection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.feecollection')),
                ('hostel_allocation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.hostelallocation')),
                ('personal_contact_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.personalcontactdetail')),
                ('personal_details', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.personaldetails')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.qualification')),
                ('transport_allocation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.transportallocation')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAdmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('reg_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Admission No:')),
                ('date', models.DateField(verbose_name='Admission date')),
                ('application_form_no', models.CharField(max_length=100, verbose_name='Application Form No:')),
                ('roll', models.IntegerField()),
                ('class_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='classes.class')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('stream', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='classes.stream')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.studentregistration')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplines_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('finish_time', models.TimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.disciplines', verbose_name='discipline_detail')),
            ],
            options={
                'verbose_name': 'Discipline details',
                'verbose_name_plural': 'Disciplines details',
            },
        ),
        migrations.AddField(
            model_name='disciplines',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentregistration', verbose_name='student_discipline'),
        ),
        migrations.AddField(
            model_name='disciplines',
            name='type',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.discipline_type', verbose_name='discipline_type'),
        ),
        migrations.CreateModel(
            name='Attendances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('type', models.IntegerField(choices=[('', 'Please select'), ('present', 'Present'), ('absent', 'Absent')], default=0)),
                ('motif', models.TextField(blank=True, null=True)),
                ('is_excused', models.BooleanField(default=False)),
                ('justification', models.TextField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='', verbose_name='document_attendance')),
                ('start_date', models.DateField(default=datetime.date.today, null=True)),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentregistration', verbose_name='student_attendance')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'ordering': ('-start_date', '-modified_at'),
            },
        ),
    ]
