# Generated by Django 3.1 on 2020-12-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20201204_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='place_of_birth',
            field=models.CharField(default='moro', max_length=200, verbose_name='Place of Birth'),
        ),
    ]
