# Generated by Django 3.1 on 2020-12-02 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20201127_1654'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0002_personaldetails_place_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='Allocation Date')),
                ('vehicle', models.CharField(max_length=200, verbose_name='Vehicle name')),
                ('route', models.CharField(max_length=200, verbose_name='Route')),
                ('boarding_point', models.CharField(max_length=200, verbose_name='Boarding Point Name')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAdmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('reg_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Admission No:')),
                ('date', models.DateField(verbose_name='Admission date')),
                ('application_form_no', models.CharField(max_length=100, verbose_name='Application Form No:')),
                ('class_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='classes.class')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('stream', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='classes.stream')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('school_name', models.CharField(max_length=100, verbose_name='School Name')),
                ('date_admission', models.DateField(verbose_name='Admission Date')),
                ('date_leaving', models.DateField(verbose_name='Leaving Date')),
                ('last_exam', models.CharField(max_length=200, verbose_name='Last Attending Examination')),
                ('other_qualification', models.CharField(max_length=200, verbose_name='Other Qualification')),
                ('remarks', models.TextField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalContactDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('p_address', models.TextField(verbose_name='Address')),
                ('p_postal_code', models.CharField(max_length=50, verbose_name='Postal Code')),
                ('p_country', django_countries.fields.CountryField(default='TZ', max_length=2, verbose_name='Country')),
                ('p_phone', models.CharField(max_length=14, verbose_name='Phone')),
                ('student_email', models.EmailField(max_length=254, verbose_name='Student Email')),
                ('pr_address', models.TextField(verbose_name='Address')),
                ('pr_postal_code', models.CharField(max_length=50, verbose_name='Postal Code')),
                ('pr_country', django_countries.fields.CountryField(default='TZ', max_length=2, verbose_name='Country')),
                ('pr_phone', models.CharField(max_length=14, verbose_name='Phone')),
                ('parent_email', models.EmailField(max_length=254, verbose_name='Parent Address')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hostelallocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(choices=[('', 'Please select'), ('male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('date', models.DateField(verbose_name='Allocation Date')),
                ('hostel_name', models.CharField(max_length=200, verbose_name='Hostel Name')),
                ('block_name', models.CharField(max_length=200, verbose_name='Block Name')),
                ('room_name', models.CharField(max_length=200, verbose_name='Room Name')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeeCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('payment_mode', models.CharField(choices=[('', 'Please select'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('draft', 'Draft')], max_length=50, verbose_name='Payment Mode')),
                ('bank', models.CharField(max_length=200)),
                ('cheque', models.CharField(max_length=200)),
                ('receipt', models.CharField(max_length=200)),
                ('reg_fee_amount', models.CharField(max_length=200)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
