# Generated by Django 3.1 on 2020-12-03 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_feecollection_hostelallocation_personalcontactdetail_qualification_studentadmission_transportallocat'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feecollection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.feecollection')),
                ('hostel_allocation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.hostelallocation')),
                ('personal_contact_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.personalcontactdetail')),
                ('personal_details', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.personaldetails')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.qualification')),
                ('student_admission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.studentadmission')),
                ('transport_allocation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.transportallocation')),
            ],
        ),
    ]
