# Generated by Django 3.1 on 2020-12-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20201204_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feecollection',
            name='bank',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='feecollection',
            name='cheque',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
