# Generated by Django 3.1 on 2020-12-03 13:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20201127_1654'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0004_studentregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('punishment', models.CharField(max_length=100, null=True)),
                ('start_date', models.BooleanField(default=True)),
                ('end_date', models.BooleanField(default=True)),
                ('start_time', models.BooleanField(default=True)),
                ('end_time', models.BooleanField(default=False)),
                ('repeatable', models.BooleanField(default=True)),
                ('alert', models.PositiveSmallIntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Discipline's type",
                'verbose_name_plural': "Discipline's types",
                'ordering': ('punishment',),
            },
        ),
        migrations.CreateModel(
            name='Disciplines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('motif', models.TextField(blank=True, null=True)),
                ('fact_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive'), ('done', 'Done'), ('cancelled', 'cancelled')], default='Active', max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.CharField(blank=True, max_length=250, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentregistration', verbose_name='student_discipline')),
                ('type', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.discipline_type', verbose_name='discipline_type')),
            ],
            options={
                'verbose_name': 'Discipline',
                'verbose_name_plural': 'Disciplines',
                'ordering': ('-fact_date',),
            },
        ),
        migrations.CreateModel(
            name='EnrolledStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('roll', models.IntegerField()),
                ('class_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='classes.class')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('stream', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='classes.stream')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.studentregistration')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplines_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('finish_time', models.TimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.disciplines', verbose_name='discipline_detail')),
            ],
            options={
                'verbose_name': 'Discipline details',
                'verbose_name_plural': 'Disciplines details',
            },
        ),
        migrations.CreateModel(
            name='Attendances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('type', models.IntegerField(choices=[('', 'Please select'), ('present', 'Present'), ('absent', 'Absent')], default=0)),
                ('motif', models.TextField(blank=True, null=True)),
                ('is_excused', models.BooleanField(default=False)),
                ('justification', models.TextField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='', verbose_name='document_attendance')),
                ('start_date', models.DateField(default=datetime.date.today, null=True)),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentregistration', verbose_name='student_attendance')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'ordering': ('-start_date', '-modified_at'),
            },
        ),
    ]
