# Generated by Django 3.1 on 2020-12-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20201204_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentadmission',
            name='application_form_no',
            field=models.CharField(max_length=100, unique=True, verbose_name='Application Form No:'),
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='reg_no',
            field=models.CharField(max_length=100, unique=True, verbose_name='Registration No:'),
        ),
    ]
