# Generated by Django 3.1 on 2020-12-07 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_disciplines_last_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discipline_type',
            options={'ordering': ('sanction',), 'verbose_name': "Discipline's type", 'verbose_name_plural': "Discipline's types"},
        ),
        migrations.RenameField(
            model_name='discipline_type',
            old_name='punishment',
            new_name='sanction',
        ),
        migrations.AlterField(
            model_name='disciplines',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentadmission', verbose_name='student_discipline'),
        ),
    ]
