# Generated by Django 3.1 on 2020-12-07 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_auto_20201207_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discipline_type',
            options={'ordering': ('sunction',), 'verbose_name': "Discipline's type", 'verbose_name_plural': "Discipline's types"},
        ),
        migrations.RenameField(
            model_name='discipline_type',
            old_name='sanction',
            new_name='sunction',
        ),
    ]
