# Generated by Django 3.1 on 2020-11-27 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='department',
        ),
    ]
