# Generated by Django 3.1 on 2020-11-27 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0010_auto_20201126_1803'),
        ('classes', '0002_remove_class_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='select_class',
        ),
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master.department'),
            preserve_default=False,
        ),
    ]
