# Generated by Django 3.1 on 2020-12-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20201204_1843'),
        ('classes', '0003_auto_20201127_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='leaders',
            field=models.ManyToManyField(to='students.StudentRegistration'),
        ),
    ]
