# Generated by Django 3.1 on 2020-12-05 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
        ('classes', '0005_auto_20201205_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsyllabus',
            name='no_parts',
            field=models.IntegerField(default=1, verbose_name='No. of parts'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classsyllabus',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher', verbose_name='Teacher'),
        ),
    ]
