# Generated by Django 3.1 on 2020-12-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_auto_20201205_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classsyllabus',
            name='components',
        ),
        migrations.AddField(
            model_name='classsyllabus',
            name='assignment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classsyllabus',
            name='practical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classsyllabus',
            name='project',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classsyllabus',
            name='theory',
            field=models.BooleanField(default=False),
        ),
    ]
