# Generated by Django 3.1 on 2020-12-06 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_auto_20201206_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classsyllabus',
            name='teacher',
        ),
    ]
