# Generated by Django 3.1 on 2020-12-06 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_remove_classsyllabus_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classsyllabus',
            name='no_parts',
        ),
    ]
