# Generated by Django 3.1 on 2020-12-06 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0009_remove_classsyllabus_no_parts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classsyllabus',
            name='created_by',
        ),
    ]
