# Generated by Django 3.1 on 2020-12-06 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0010_remove_classsyllabus_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsyllabus',
            name='select_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.class'),
        ),
    ]
