# Generated by Django 3.1 on 2020-12-06 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0012_classsyllabus_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classsyllabus',
            name='created_by',
        ),
    ]
