# Generated by Django 3.1 on 2020-12-06 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0013_remove_classsyllabus_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='last_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
