# Generated by Django 3.1 on 2020-12-07 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0015_auto_20201206_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='leaders',
        ),
    ]
