# Generated by Django 3.1 on 2020-12-08 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0017_subjectpart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0014_auto_20201207_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, verbose_name='Division Name')),
                ('percentage_from', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percentage From')),
                ('percentage_to', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percentage To')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExamMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Exam Name')),
                ('enter_code', models.CharField(max_length=50, verbose_name='Enter Examination Code')),
                ('select_term', models.CharField(choices=[('', 'please select'), ('term_one', 'Term 1'), ('term_two', 'Term 2')], max_length=50, verbose_name='Select Term')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('select_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.class')),
            ],
        ),
        migrations.CreateModel(
            name='ExamSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('assignment_marks_min', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Assignment Marks Min')),
                ('assignment_marks_max', models.DecimalField(decimal_places=2, default=100.0, max_digits=18, verbose_name='Assignment Marks Max')),
                ('theory_marks_min', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Theory Marks min')),
                ('theory_marks_max', models.DecimalField(decimal_places=2, default=100.0, max_digits=18, verbose_name='Theory Marks max')),
                ('practical_marks_min', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Practical Marks min')),
                ('practical_marks_max', models.DecimalField(decimal_places=2, default=100.0, max_digits=18, verbose_name='Practical Marks max')),
                ('project_marks_min', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Project Marks min')),
                ('project_marks_max', models.DecimalField(decimal_places=2, default=100.0, max_digits=18, verbose_name='Project Marks max')),
                ('total_marks_max', models.DecimalField(decimal_places=2, default=100.0, max_digits=18, verbose_name='Total Marks max')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('exam_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.exammaster')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.subject')),
            ],
        ),
        migrations.CreateModel(
            name='ExamMarkMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('exam_division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.examdivision')),
                ('exam_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.examsubject')),
            ],
        ),
        migrations.CreateModel(
            name='ExamMarkEntryPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('theory_mark', models.CharField(max_length=18, verbose_name='Theory Marks')),
                ('assignment_mark', models.CharField(max_length=18, verbose_name='Assignment Marks')),
                ('practical_mark', models.CharField(max_length=18, verbose_name='Practical Marks')),
                ('project_mark', models.CharField(max_length=18, verbose_name='Project Marks')),
                ('status', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('exam_mark_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.exammarkmaster')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentadmission')),
                ('subject_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.subjectpart')),
            ],
        ),
        migrations.CreateModel(
            name='ExamMarkEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('theory_mark', models.CharField(max_length=18, verbose_name='Theory Marks')),
                ('assignment_mark', models.CharField(max_length=18, verbose_name='Assignment Marks')),
                ('practical_mark', models.CharField(max_length=18, verbose_name='Practical Marks')),
                ('project_mark', models.CharField(max_length=18, verbose_name='Project Marks')),
                ('total', models.CharField(blank=True, max_length=50, null=True, verbose_name='Total')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('exam_mark_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.exammarkmaster')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentadmission')),
                ('subject_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.subjectpart', verbose_name='Subject Part')),
            ],
        ),
        migrations.CreateModel(
            name='ExamGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, verbose_name='Enter Grade Name')),
                ('percentage_from', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percentage From')),
                ('percentage_to', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percentage To')),
                ('component', models.CharField(choices=[('', 'please select'), ('theory', 'Theory'), ('practical', 'Practical'), ('assignment', 'Assignment'), ('project', 'Project')], max_length=20, verbose_name='Component Type')),
                ('status', models.BooleanField(default=False, verbose_name='Fail Grade')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
