# Generated by Django 3.1 on 2020-12-11 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0017_subjectpart'),
        ('examination', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammarkentry',
            name='exam_mark_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='examination.exammarkmaster'),
        ),
        migrations.AlterField(
            model_name='exammarkentry',
            name='subject_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.subjectpart', verbose_name='Subject Part'),
        ),
    ]
