# Generated by Django 3.1 on 2020-12-11 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0004_exammaster_last_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammarkentry',
            name='exam_mark_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='examination.exammaster'),
        ),
    ]
