# Generated by Django 3.1 on 2020-12-11 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0006_auto_20201211_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='exammarkentry',
            name='exam_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='examination.examsubject'),
        ),
    ]
