# Generated by Django 3.1 on 2020-11-25 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master', '0003_auto_20201125_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='master',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.customuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='starting_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
