# Generated by Django 3.1 on 2020-11-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_auto_20201125_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicsession',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
