# Generated by Django 3.1 on 2020-11-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_academicsession_is_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicsession',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Close this Academic Year'),
        ),
    ]
