# Generated by Django 3.1 on 2020-11-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_auto_20201126_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='short_name',
            field=models.CharField(blank=True, max_length=10, verbose_name='Department Short Name'),
        ),
    ]
