# Generated by Django 3.1 on 2020-12-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0011_remove_school_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='school',
            name='starting_date',
        ),
        migrations.AddField(
            model_name='school',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
