# Generated by Django 3.1 on 2020-12-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0012_auto_20201204_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(default='images_4.png', upload_to='logo', verbose_name='Upload school logo'),
        ),
    ]
