# Generated by Django 3.1 on 2020-12-07 07:25

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationFormReceive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(default=True, verbose_name='Date')),
                ('serial_number', models.CharField(max_length=20, verbose_name='Serial Number')),
                ('Student_name', models.CharField(max_length=200, verbose_name='First Name')),
                ('gender', models.CharField(choices=[('', 'Please select'), ('male', 'Male'), ('Female', 'Female')], max_length=10, verbose_name='Gender')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('gurdian_name', models.CharField(max_length=200, verbose_name='Gurdian Name')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone Number')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationFormSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(default=datetime.date.today, verbose_name='Date')),
                ('form_number', models.CharField(max_length=20, verbose_name='Form Number')),
                ('serial_number', models.CharField(max_length=20, verbose_name='Serial Number')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('first_name', models.CharField(max_length=200, verbose_name='First Name')),
                ('middle_name', models.CharField(max_length=200, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last Name')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone Number')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(default=True, verbose_name='Date')),
                ('phone_status', models.CharField(choices=[('', 'Please select'), ('received', 'Received'), ('dialed', 'Dialed')], max_length=10, verbose_name='Phone_status')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone Number')),
                ('reference_person_name', models.CharField(max_length=50, verbose_name='Reference Person Name')),
                ('reference_person_remarks', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VisitorsEnquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('enquiry_date', models.DateTimeField(default=True, verbose_name='Enquiry Date')),
                ('visitor_name', models.CharField(max_length=200, verbose_name='Visitor Name')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone Number')),
                ('description', models.TextField()),
                ('Student_name', models.CharField(max_length=200, verbose_name='Student Name')),
                ('admission_number', models.CharField(max_length=200, verbose_name='Admission Number')),
                ('staff_name', models.CharField(max_length=200, verbose_name='Staff Name')),
                ('designations', models.CharField(max_length=50, verbose_name='Designations')),
            ],
        ),
    ]
