# Generated by Django 3.1 on 2020-12-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationformsale',
            name='form_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Form Number'),
        ),
        migrations.AlterField(
            model_name='applicationformsale',
            name='serial_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Serial Number'),
        ),
    ]
