# Generated by Django 3.1 on 2020-12-07 11:26

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0002_auto_20201207_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationformreceive',
            name='application_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, verbose_name='Application Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicationformreceive',
            name='date',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
